import Head from "next/head";
import Link from "next/link";
import AccountStatus from "./AccountStatus";

const DefaultLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <title>TXHT - Thanks Token</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="p-0 navbar">
        <div className="flex-none w-1/4">
          <Link href="/">
            <a className="px-4 text-xl normal-case btn btn-ghost hover:bg-base-300">
              THXT
            </a>
          </Link>
        </div>
        <div className="flex-1 w-1/2">
          <AccountStatus />
        </div>
      </div>
      <div className="container mx-auto">{children}</div>
    </>
  );
};

export default DefaultLayout;
